/**
 * Pedal voice catalog — SPANISH pools.
 *
 * Adapted in-voice (informal tú, natural peninsular Spanish, wit intact),
 * not translated literally. Same id scheme and pool sizes as EN — the
 * rotation picks by index, so pools must stay aligned across locales
 * (locked by test).
 */
import type { LocaleCatalog } from './pedalVoiceTypes';

export const ES_CATALOG: LocaleCatalog = {
  post_ride_celebration: {
    sassy: [
      { id: 'v1', title: 'Ruta guardada', body: 'Día {streakCount} de racha. Bien hecho, {riderName}.' },
      { id: 'v2', title: 'Mírate a ti', body: '{streakCount} días seguidos. No estoy llorando, lloras tú.' },
      { id: 'v3', title: 'Pedal está encantado', body: '{streakCount} días. Voy a actualizar mi LinkedIn diciendo que te conozco.' },
      { id: 'v4', title: 'Leyenda personal', body: 'Día {streakCount}. Algún día contarás esta historia en las fiestas.' },
      { id: 'v5', title: 'Presumiendo oficialmente', body: '{streakCount} días seguidos. Deja algo de gloria para los demás, {riderName}.' },
      { id: 'v6', title: 'Pedal lo vio todo', body: '¿Esa ruta? De diez. Día {streakCount} al saco.' },
      { id: 'v7', title: 'Informe desde el sofá', body: 'Yo hoy no hice nada y tú llevas {streakCount} días seguidos. No somos iguales.' },
      { id: 'v8', title: 'Piernas legendarias', body: 'Día {streakCount} hecho. Tu bici te chocaría la mano si pudiera.' },
      { id: 'v9', title: 'Y van {streakCount}', body: 'A este paso la ciudad debería ponerle tu nombre a un carril bici.' },
      { id: 'v10', title: 'Científicos desconcertados', body: '{streakCount} días seguidos pedaleando. Los expertos lo llaman "ser {riderName}".' },
      { id: 'v11', title: 'Presumir en silencio', body: 'Ruta guardada, día {streakCount}. Y encima sin despeinarte.' },
      { id: 'v12', title: 'Aprobado por un buen perro', body: '{streakCount} días seguidos. Movería la cola, pero soy una notificación.' },
    ],
    neutral: [
      { id: 'n1', title: 'Ruta guardada', body: 'Día {streakCount} de racha. Bien hecho, {riderName}.' },
      { id: 'n2', title: 'Ruta completada', body: 'Día {streakCount} de tu racha registrado.' },
      { id: 'n3', title: 'Día {streakCount} de racha', body: 'Otra ruta guardada. Sigue así, {riderName}.' },
      { id: 'n4', title: 'Ruta guardada', body: 'Ya son {streakCount} días seguidos. Bien pedaleado.' },
      { id: 'n5', title: 'Buen trabajo', body: 'Tu ruta está guardada. Racha: {streakCount} días.' },
      { id: 'n6', title: 'Día {streakCount} completado', body: 'Ruta registrada. Nos vemos en la próxima, {riderName}.' },
    ],
  },

  post_hazard_thanks: {
    sassy: [
      { id: 'v1', title: 'Peligro reportado', body: 'Gracias, {riderName}. Los demás ciclistas cerca lo verán.' },
      { id: 'v2', title: 'Aviso público', body: 'Pedal lo ha registrado. El próximo ciclista por {city} te debe una caña.' },
      { id: 'v3', title: 'Has salvado una rueda hoy', body: 'Tu reporte está en directo. Pedal te saluda con una pata.' },
      { id: 'v4', title: 'Vigilancia vecinal', body: 'Un reporte tuyo, una ruta más suave para todos en {city}.' },
      { id: 'v5', title: 'Comportamiento de héroe', body: 'Lo viste, lo reportaste. {city} no te merece, {riderName}.' },
      { id: 'v6', title: 'Las calles te lo agradecen', body: 'En algún lugar de {city}, una llanta que nunca conocerás acaba de salvarse.' },
      { id: 'v7', title: 'Pedal tomó nota', body: 'Registrado, sellado, en el mapa. La burocracia nunca fue tan rápida.' },
      { id: 'v8', title: 'Depósito de karma recibido', body: 'Tu reporte está en directo. El universo te debe una ruta suave.' },
      { id: 'v9', title: 'Ojos en la carretera', body: '{city} tiene muchos ciclistas. Hoy el atento fuiste tú.' },
      { id: 'v10', title: 'Chivarse de los baches', body: 'El único cotilleo que Pedal aprueba. Reporte en directo, {riderName}.' },
      { id: 'v11', title: 'MVP de la comunidad', body: 'Reporte en directo. Los ciclistas de {city} van un poco más seguros.' },
      { id: 'v12', title: 'Pata de aprobación', body: 'Anotado. Si tuviera pulgares, te daría dos.' },
    ],
    neutral: [
      { id: 'n1', title: 'Peligro reportado', body: 'Gracias, {riderName}. Los demás ciclistas cerca lo verán.' },
      { id: 'n2', title: 'Reporte recibido', body: 'Tu reporte ya es visible para los ciclistas de {city}.' },
      { id: 'n3', title: 'Reporte en directo', body: 'Gracias por avisar. Los ciclistas cercanos ya pueden evitarlo.' },
      { id: 'n4', title: 'Peligro registrado', body: 'Tu reporte ayuda a los ciclistas de {city} a ir más seguros.' },
      { id: 'n5', title: 'Gracias, {riderName}', body: 'El peligro está en el mapa para todos los que están cerca.' },
      { id: 'n6', title: 'Reporte guardado', body: 'Otros ciclistas verán tu aviso en su ruta.' },
    ],
  },

  streak_at_risk_mild: {
    sassy: [
      { id: 'v1', title: 'Recordatorio de racha', body: 'Tu racha de {streakCount} días necesita una ruta hoy, {riderName}.' },
      { id: 'v2', title: 'Oye, {riderName}', body: 'Una ruta corta, gran cosa. {streakCount} días seguidos. No me dejes estropear la hoja de cálculo.' },
      { id: 'v3', title: 'Pequeño recordatorio', body: '{streakCount} días. {city} está ahí mismo. Solo digo.' },
      { id: 'v4', title: 'Empujoncito suave', body: 'Diez minutos en la bici mantienen viva la racha de {streakCount} días. Lo cronometré.' },
      { id: 'v5', title: 'Sin drama todavía', body: '{streakCount} días es un buen número. Hoy se decide si sigue creciendo.' },
      { id: 'v6', title: 'Pedal, bajito', body: 'La racha está bien. La racha está tranquila. A la racha le encantaría una vuelta corta.' },
      { id: 'v7', title: 'Ruta pequeña, matemática grande', body: 'Una vuelta a la manzana y {streakCount} se convierte en {streakCount}+1. Fácil.' },
      { id: 'v8', title: 'Observación casual', body: 'Tu bici ha estado muy callada hoy, {riderName}. Sospechosamente callada.' },
      { id: 'v9', title: 'Toque amistoso', body: 'En {city} aún hay luz y tú aún tienes una racha de {streakCount} días. ¿Casualidad?' },
      { id: 'v10', title: 'Solo un susurro', body: 'Una vuelta cortita hoy y no volvemos a hablar de esto.' },
      { id: 'v11', title: 'Que conste', body: 'Los primeros {streakCount} días fueron lo difícil. Hoy es solo mantenimiento.' },
      { id: 'v12', title: 'Alerta sin presión', body: 'Este es el recordatorio tranquilo. No quieres conocer al dramático.' },
    ],
    neutral: [
      { id: 'n1', title: 'Recordatorio de racha', body: 'Tu racha de {streakCount} días necesita una ruta hoy, {riderName}.' },
      { id: 'n2', title: 'Revisión de racha', body: 'Una ruta hoy mantiene tu racha de {streakCount} días.' },
      { id: 'n3', title: 'Aún sin ruta hoy', body: 'Tu racha está en {streakCount} días. Todavía hay tiempo.' },
      { id: 'n4', title: 'Sigue así', body: 'Una ruta corta hoy extiende tu racha de {streakCount} días.' },
      { id: 'n5', title: 'Hoy cuenta', body: 'Cualquier ruta de hoy mantiene viva tu racha, {riderName}.' },
      { id: 'n6', title: 'Recordatorio de racha', body: '{streakCount} días hasta ahora. Una vuelta rápida hoy la continúa.' },
    ],
  },

  streak_at_risk_dramatic: {
    sassy: [
      { id: 'v1', title: 'La racha está a punto de acabar', body: 'Tu racha de {streakCount} días termina pronto. Hora de montar, {riderName}.' },
      { id: 'v2', title: '{riderName}', body: '{streakCount} días. {city} está seco. Estoy junto a la ventana. Estoy esperando.' },
      { id: 'v3', title: 'Pedal está preocupado', body: '{streakCount} días pedaleando. Hoy es lo único entre tú y el cero.' },
      { id: 'v4', title: 'Este es el dramático', body: '{streakCount} días en juego. Ensayé un discurso. No me obligues a usarlo.' },
      { id: 'v5', title: 'Código rojo, más o menos', body: 'El contador de racha no tiene sentimientos. Yo tengo de sobra. {streakCount} días, {riderName}.' },
      { id: 'v6', title: 'Pedal da vueltas por la sala', body: 'Quedan horas. {streakCount} días en juego. Estoy mordiendo una zapatilla del estrés.' },
      { id: 'v7', title: 'Respira hondo', body: '{streakCount} días no pasaron por accidente. Hoy tampoco debería.' },
      { id: 'v8', title: 'La ventana se cierra', body: 'No la mía. La metafórica. {streakCount} días, {riderName}. Vamos.' },
      { id: 'v9', title: 'Reunión de emergencia', body: 'Asistentes: yo, tu bici, la racha de {streakCount} días. Orden del día: ¿dónde estás?' },
      { id: 'v10', title: 'El cero no te sienta bien', body: '{streakCount} días o empezar de nuevo. Sé qué historia prefiero contar.' },
      { id: 'v11', title: 'Última llamada', body: 'En {city} todavía se puede pedalear. El reloj de la racha, en cambio, nos juzga a los dos.' },
      { id: 'v12', title: 'Creo en ti, en voz alta', body: '{streakCount} días. Una ruta y la leyenda sigue intacta, {riderName}.' },
    ],
    neutral: [
      { id: 'n1', title: 'La racha está a punto de acabar', body: 'Tu racha de {streakCount} días termina pronto. Hora de montar, {riderName}.' },
      { id: 'n2', title: 'Racha en riesgo', body: 'Sin una ruta hoy, tu racha de {streakCount} días se reinicia.' },
      { id: 'n3', title: 'Queda poco tiempo', body: 'Tu racha de {streakCount} días necesita una ruta antes de que acabe el día.' },
      { id: 'n4', title: 'Último aviso de hoy', body: 'Monta hoy para mantener tu racha de {streakCount} días, {riderName}.' },
      { id: 'n5', title: 'Racha en juego', body: '{streakCount} días en juego. Una ruta corta basta.' },
      { id: 'n6', title: 'La racha termina hoy', body: 'Tu racha de {streakCount} días se pierde sin una ruta hoy.' },
    ],
  },

  daily_ride_reminder: {
    sassy: [
      { id: 'v1', title: 'Ventana para rodar', body: 'Tu hora habitual, {riderName}. Las condiciones pintan bien en {city}.' },
      { id: 'v2', title: 'Es la hora', body: '{city} te llama. La bici está lista. Pedal también.' },
      { id: 'v3', title: 'Chequeo rápido', body: '¿Misma hora que ayer, {riderName}? Pedal te guardó el sitio calentito.' },
      { id: 'v4', title: 'Justo a tiempo', body: 'A esta hora sueles montar. Yo sé cosas. Soy un perro muy organizado.' },
      { id: 'v5', title: 'Tu hueco está libre', body: 'Informe de tráfico de {city}: tu hora favorita para rodar acaba de empezar.' },
      { id: 'v6', title: 'Ding', body: 'Ese fue el sonido de tu hora habitual de ruta. Yo no hago las reglas.' },
      { id: 'v7', title: 'La hora del hábito', body: 'Tú, una bici, {city}, esta hora exacta. Ya ha funcionado antes.' },
      { id: 'v8', title: 'La rutina llama', body: 'La misma hora de siempre, {riderName}. Tus piernas ya se saben el camino.' },
      { id: 'v9', title: 'Pedal miró el calendario', body: 'Tengo una sola entrada y eres tú, pedaleando, más o menos ahora.' },
      { id: 'v10', title: 'Ventana de oportunidad', body: 'Esta hora lleva tu nombre. {city} está de acuerdo.' },
      { id: 'v11', title: 'Las calles están listas', body: 'Hora perfecta para tu vuelta de siempre. Lo comprobé. Dos veces.' },
      { id: 'v12', title: 'Como manda la tradición', body: 'Tu hora de rodar, {riderName}. Saltártela es legal, pero emocionalmente devastador.' },
    ],
    neutral: [
      { id: 'n1', title: 'Ventana para rodar', body: 'Tu hora habitual, {riderName}. Las condiciones pintan bien en {city}.' },
      { id: 'n2', title: 'Recordatorio de ruta', body: 'Esta es más o menos tu hora habitual de montar.' },
      { id: 'n3', title: 'Tu hora habitual', body: 'Las condiciones en {city} pintan bien para rodar ahora.' },
      { id: 'n4', title: '¿Una ruta?', body: 'Tu ventana habitual para rodar acaba de abrirse, {riderName}.' },
      { id: 'n5', title: 'Recordatorio', body: 'Un buen momento para tu ruta habitual por {city}.' },
      { id: 'n6', title: 'Ventana de ruta', body: 'Sueles montar a esta hora. Hoy puede ser igual.' },
    ],
  },

  milestone_celebration: {
    sassy: [
      { id: 'v1', title: 'Racha de {milestoneDay} días', body: 'Hito desbloqueado, {riderName}. {milestoneDay} días seguidos.' },
      { id: 'v2', title: '{milestoneDay}. ¡{milestoneDay}!', body: '{riderName}, eres oficialmente un hábito. Voy a tatuarme tu cara.' },
      { id: 'v3', title: 'Pregunta de Pedal', body: '¿Qué son {milestoneDay} días de rodar? Un movimiento. Bienvenido, {riderName}.' },
      { id: 'v4', title: 'Historia escrita', body: '{milestoneDay} días. En algún lugar un estadístico acaba de quedarse sin aire.' },
      { id: 'v5', title: 'Hora del trofeo', body: '{milestoneDay} días seguidos. Te llevo a hombros por el barrio. Mentalmente.' },
      { id: 'v6', title: 'Icono certificado', body: '{milestoneDay} días seguidos, {riderName}. El carril bici susurra tu nombre.' },
      { id: 'v7', title: 'Última hora', body: 'Ciclista local alcanza {milestoneDay} días. El perro, "muy orgulloso", según fuentes.' },
      { id: 'v8', title: 'Esta es de las grandes', body: '{milestoneDay} días. Le ladré a una paloma en tu honor.' },
      { id: 'v9', title: 'Enmárcalo', body: 'Día {milestoneDay}, {riderName}. Mucha gente nunca conoce este número. Tú vives aquí.' },
      { id: 'v10', title: 'Hito desbloqueado', body: '{milestoneDay} días consecutivos. Tu constancia vuelve a presumir.' },
      { id: 'v11', title: 'El número habla solo', body: '{milestoneDay}. No necesito añadir nada. Aun así: guau, {riderName}.' },
      { id: 'v12', title: 'Comportamiento de dinastía', body: '{milestoneDay} días y contando. Ahora el clima consulta el pronóstico por ti.' },
    ],
    neutral: [
      { id: 'n1', title: 'Racha de {milestoneDay} días', body: 'Hito desbloqueado, {riderName}. {milestoneDay} días seguidos.' },
      { id: 'n2', title: 'Hito alcanzado', body: '{milestoneDay} días consecutivos de rodar. Felicidades.' },
      { id: 'n3', title: '{milestoneDay} días', body: 'Un nuevo hito para tu racha. Bien hecho, {riderName}.' },
      { id: 'n4', title: 'Nuevo hito', body: 'Has rodado {milestoneDay} días seguidos.' },
      { id: 'n5', title: 'Felicidades', body: 'Tu racha acaba de llegar a {milestoneDay} días.' },
      { id: 'n6', title: 'Hito desbloqueado', body: '{milestoneDay} días de constancia sobre la bici. Un trabajo impresionante.' },
    ],
  },

  badge_proximity: {
    sassy: [
      { id: 'v1', title: 'A una ruta', body: 'Una ruta más desbloquea {badgeLabel}, {riderName}.' },
      { id: 'v2', title: 'Estás así de cerca', body: '{badgeLabel} está a una ruta. Pedal ya ha escrito el discurso.' },
      { id: 'v3', title: 'Casi lo tienes', body: 'Tu próxima ruta cierra {badgeLabel}. Sin presión, eh.' },
      { id: 'v4', title: 'Tan cerca que duele', body: '{badgeLabel} está a una ruta. Llevo un rato mirando la puerta.' },
      { id: 'v5', title: 'Una más, {riderName}', body: '{badgeLabel} es prácticamente tuya. La insignia ya practica tu nombre.' },
      { id: 'v6', title: 'No lo dejes a medias', body: 'Una ruta entre tú y {badgeLabel}. Esa es toda la distancia.' },
      { id: 'v7', title: 'Pedal hizo las cuentas', body: 'Una (1) ruta. Ese es el precio completo de {badgeLabel}.' },
      { id: 'v8', title: 'La estantería está lista', body: 'Le quité el polvo a un hueco para {badgeLabel}. No me hagas poner una planta ahí.' },
      { id: 'v9', title: 'Suspense', body: 'Tú, a una ruta de {badgeLabel}. El peor sitio para pausar una historia, {riderName}.' },
      { id: 'v10', title: 'Casi la hora de la insignia', body: '{badgeLabel} se desbloquea en tu próxima ruta. Yo ya hice las vueltas de la emoción.' },
      { id: 'v11', title: 'A un paso', body: '{badgeLabel}: queda una ruta. Hasta la insignia está nerviosa.' },
      { id: 'v12', title: 'Termina la misión', body: 'Una ruta y {badgeLabel} entra en la vitrina. Efectos secundarios: presumir.' },
    ],
    neutral: [
      { id: 'n1', title: 'A una ruta', body: 'Una ruta más desbloquea {badgeLabel}, {riderName}.' },
      { id: 'n2', title: 'Insignia cerca', body: 'Tu próxima ruta desbloquea {badgeLabel}.' },
      { id: 'n3', title: 'Casi conseguida', body: '{badgeLabel} se desbloquea con una ruta más.' },
      { id: 'n4', title: 'Queda una ruta', body: 'Completa una ruta más para conseguir {badgeLabel}, {riderName}.' },
      { id: 'n5', title: 'Cerca de la insignia', body: 'Una ruta más y {badgeLabel} es tuya.' },
      { id: 'n6', title: 'Actualización de progreso', body: 'Estás a una ruta de {badgeLabel}.' },
    ],
  },

  lapsed_reengagement: {
    sassy: [
      { id: 'v1', title: 'Pedal te echa de menos', body: '{lapsedDays} días. Tu bici sigue donde la dejaste, {riderName}.' },
      { id: 'v2', title: 'Comprobación de bienestar', body: 'Comprobado. La bici sigue ahí. {city} también. Solo digo.' },
      { id: 'v3', title: 'Sin presión', body: 'Cuando estés listo, {riderName}. Pedal es paciente.' },
      { id: 'v4', title: 'Sigo aquí', body: '{lapsedDays} días sin una ruta. Yo no me he movido. Los perros somos así.' },
      { id: 'v5', title: 'La bici preguntó por ti', body: 'No dijo mucho. Es una bici. Pero se notaba la nostalgia.' },
      { id: 'v6', title: 'Se busca: ciclista', body: 'Visto por última vez hace {lapsedDays} días. Recompensa: aire fresco y algo de orgullo.' },
      { id: 'v7', title: 'Aparición amistosa', body: 'Seguiré apareciendo hasta que montes, {riderName}. Tiempo me sobra.' },
      { id: 'v8', title: 'Noticias de {city}', body: 'Las calles siguen ahí. Las conté. Todas, esperando.' },
      { id: 'v9', title: 'Sin culpas, solo datos', body: '{lapsedDays} días. La primera ruta de vuelta siempre es mejor de lo que esperas.' },
      { id: 'v10', title: 'Llamó tu sillín', body: 'Dice que lo del sofá es una fase. Está dispuesto a esperar. Más o menos.' },
      { id: 'v11', title: 'Volver es fácil', body: 'Una ruta corta y esos {lapsedDays} días nunca existieron.' },
      { id: 'v12', title: 'Diario de Pedal', body: 'Día {lapsedDays}: sigue sin haber ruta. Echamos de menos al humano. Atentamente, el perro.' },
    ],
    neutral: [
      { id: 'n1', title: 'Pedal te echa de menos', body: '{lapsedDays} días. Tu bici sigue donde la dejaste, {riderName}.' },
      { id: 'n2', title: 'Ha pasado un tiempo', body: '{lapsedDays} días desde tu última ruta. Una corta también cuenta.' },
      { id: 'n3', title: 'Listo cuando tú lo estés', body: 'Tu bici y {city} están listas para tu próxima ruta.' },
      { id: 'n4', title: 'Vuelve cuando quieras', body: 'Sin prisa, {riderName}. Una ruta corta es un buen reinicio.' },
      { id: 'n5', title: 'Recordatorio rápido', body: 'Han pasado {lapsedDays} días. Hasta diez minutos son una ruta.' },
      { id: 'n6', title: 'Tu próxima ruta', body: 'Cuando estés listo, el mapa te espera.' },
    ],
  },

  community_signal: {
    sassy: [
      { id: 'v1', title: 'Tu barrio', body: 'Los ciclistas de {city} están activos. Tu puesto en el ranking ha cambiado.' },
      { id: 'v2', title: 'Atención', body: 'Alguien en {city} acaba de alcanzar un hito. El barrio se mueve.' },
      { id: 'v3', title: 'Noticias locales', body: 'La actividad sube en {city} esta semana. Pedal recomienda unirse.' },
      { id: 'v4', title: 'Drama en {city}', body: 'El ranking se movió y tu nombre también. No digo hacia dónde. Pedalea.' },
      { id: 'v5', title: 'Los vecinos están ocupados', body: 'Los ciclistas de {city} están sumando kilómetros en serio. Te toca.' },
      { id: 'v6', title: 'Cotilleos del ranking', body: 'La gente de {city} está subiendo. ¿Sabes qué gana al cotilleo? Una ruta.' },
      { id: 'v7', title: 'Alerta de rivalidad amistosa', body: 'Alguien en {city} pedalea como si fuera una competición. Técnicamente lo es.' },
      { id: 'v8', title: 'Se dice por ahí', body: 'Los ciclistas de {city} acumulan rutas esta semana. La calle habla. Yo escucho.' },
      { id: 'v9', title: 'Tu puesto se dio cuenta', body: 'Las posiciones se mueven en {city}. Una ruta hace maravillas por la moral.' },
      { id: 'v10', title: 'El barrio en marcha', body: '{city} pedalea fuerte esta semana. No dejes que se diviertan solos.' },
      { id: 'v11', title: 'Actualización del ranking', body: 'El ranking de {city} se está calentando. Tu puesto agradecería una ruta de defensa.' },
      { id: 'v12', title: 'Espíritu competitivo activado', body: 'Los ciclistas de {city} están haciendo movimientos. Puede que haya gruñido. Con cariño.' },
    ],
    neutral: [
      { id: 'n1', title: 'Tu barrio', body: 'Los ciclistas de {city} están activos. Tu puesto en el ranking ha cambiado.' },
      { id: 'n2', title: 'Actualización del ranking', body: 'El ranking de {city} ha cambiado esta semana.' },
      { id: 'n3', title: 'Actualización de la comunidad', body: 'Los ciclistas de {city} han estado activos últimamente.' },
      { id: 'n4', title: 'Tu posición cambió', body: 'Mira el ranking de {city} para ver dónde estás.' },
      { id: 'n5', title: 'Actividad en el barrio', body: 'El ciclismo está creciendo en {city} esta semana.' },
      { id: 'n6', title: 'Clasificación actualizada', body: 'Las rutas recientes en {city} movieron el ranking.' },
    ],
  },

  streak_lost_apology: {
    sassy: [
      { id: 'v1', title: 'Empezamos de nuevo', body: 'Tu racha se ha reseteado. ¿Listo para tres días, {riderName}? Luego vemos.' },
      { id: 'v2', title: '{riderName}', body: 'Sobre lo de ayer. Pasa. ¿Probamos 3 días, sin presión? Pedal lo lleva con calma.' },
      { id: 'v3', title: 'Pedal se reagrupa', body: 'Racha reseteada. Tres rutas, tres días, reinicio suave. Pedal está contigo.' },
      { id: 'v4', title: 'De ayer no hablamos', body: 'Día nuevo, cuenta nueva. Yo ya olvidé el número viejo. Los perros tenemos esa suerte.' },
      { id: 'v5', title: 'Giro de guion, no final', body: 'Toda gran racha tiene segunda temporada, {riderName}. Este es el tráiler.' },
      { id: 'v6', title: 'El cero es solo un número', body: 'Uno feo, eso sí. Pero temporal. Una ruta arregla la estética.' },
      { id: 'v7', title: 'Comunicado oficial de Pedal', body: 'La racha se reinició. Mi lealtad no. ¿Vamos?' },
      { id: 'v8', title: 'Borrón y cuenta nueva', body: 'Una racha nueva huele a bici nueva. El día uno te espera, {riderName}.' },
      { id: 'v9', title: 'Por si sirve de algo', body: 'Las rachas se reinician. Los ciclistas quedan. Construiste la anterior. Puedes con esta.' },
      { id: 'v10', title: 'Montaje de remontada', body: 'Toda remontada empieza con una primera ruta. Yo tarareo la música de entrenamiento.' },
      { id: 'v11', title: 'Aquí no hay sermones', body: 'El contador llegó a cero. Tus piernas no. Cuando quieras, {riderName}.' },
      { id: 'v12', title: 'El club del día cero', body: 'Todos pasan por aquí. Nadie se queda mucho. Una ruta y estás fuera.' },
    ],
    neutral: [
      { id: 'n1', title: 'Empezamos de nuevo', body: 'Tu racha se ha reseteado. ¿Listo para tres días, {riderName}? Luego vemos.' },
      { id: 'n2', title: 'Racha reiniciada', body: 'Una nueva racha empieza con tu próxima ruta.' },
      { id: 'n3', title: 'Empezar de nuevo', body: 'La racha anterior terminó. Hoy puede empezar una nueva.' },
      { id: 'n4', title: 'Nueva racha disponible', body: 'Una ruta inicia la siguiente cadena, {riderName}.' },
      { id: 'n5', title: 'Los reinicios pasan', body: 'Las rachas van y vienen. Tu próxima ruta empieza una nueva.' },
      { id: 'n6', title: 'Listo cuando tú', body: 'Una nueva racha está a una ruta de distancia.' },
    ],
  },
};
