/**
 * courseStorage — keep imported GPX courses on the device.
 *
 * Split deliberately in two:
 *   - **Geometry on disk**, one JSON file per course. A course is a full
 *     polyline (and often per-point elevations); putting thousands of points
 *     through the Zustand persist adapter would push that payload through
 *     AsyncStorage on every unrelated state write.
 *   - **Metadata in the store**, so lists render without touching the disk.
 *
 * Files live under `documentDirectory`, NOT `cacheDirectory`: the cache is
 * evictable by the OS under storage pressure, and a course silently vanishing
 * between the ride being planned and the rider setting off is exactly the
 * failure this feature cannot have. (`gpx-share.ts` writes to the cache for
 * the opposite reason — an export is transient by design.)
 *
 * Every function swallows its failures into a null/false result. Losing a
 * course is bad; crashing the screen that lists them is worse.
 */
// Static import — a dynamic `await import()` of expo-file-system fails
// silently in Hermes release bytecode on this project. Legacy API matches the
// rest of the codebase.
import * as FileSystem from 'expo-file-system/legacy';

const COURSE_DIR_NAME = 'imported-courses';

/** Row shown in the course list. Persisted in the Zustand store. */
export interface ImportedCourseMeta {
  readonly id: string;
  readonly name: string;
  readonly distanceMeters: number;
  readonly climbMeters: number | null;
  /** Busy-road runs found at import time, so the list can warn without re-scoring. */
  readonly busyStretchCount: number;
  readonly pointCount: number;
  readonly createdAt: string;
}

/** The geometry itself, read back on demand. */
export interface StoredCourseGeometry {
  readonly coordinates: readonly [number, number][];
  readonly elevations: readonly number[] | undefined;
}

const courseDirectory = (): string | null => {
  const base = FileSystem.documentDirectory;
  return base === null ? null : `${base}${COURSE_DIR_NAME}/`;
};

const courseFile = (id: string): string | null => {
  const dir = courseDirectory();
  // `id` is generated by us, never user input, but a path separator sneaking
  // in would escape the directory — cheap to refuse outright.
  if (dir === null || id.includes('/') || id.includes('\\') || id.includes('..')) {
    return null;
  }
  return `${dir}${id}.json`;
};

const ensureDirectory = async (): Promise<boolean> => {
  const dir = courseDirectory();
  if (dir === null) return false;

  try {
    const info = await FileSystem.getInfoAsync(dir);
    if (!info.exists) {
      await FileSystem.makeDirectoryAsync(dir, { intermediates: true });
    }
    return true;
  } catch {
    return false;
  }
};

/** Identifier for a newly imported course. */
export const createCourseId = (): string =>
  `course-${Date.now()}-${Math.floor(Math.random() * 1e6).toString(36)}`;

const isStoredGeometry = (value: unknown): value is StoredCourseGeometry => {
  if (value === null || typeof value !== 'object') return false;
  const candidate = value as { coordinates?: unknown; elevations?: unknown };

  if (!Array.isArray(candidate.coordinates) || candidate.coordinates.length < 2) {
    return false;
  }
  const everyPointValid = candidate.coordinates.every(
    (point) =>
      Array.isArray(point) &&
      point.length === 2 &&
      Number.isFinite(point[0]) &&
      Number.isFinite(point[1]),
  );
  if (!everyPointValid) return false;

  if (candidate.elevations !== undefined) {
    if (!Array.isArray(candidate.elevations)) return false;
    // A partial elevation array would pair values with the wrong points —
    // the same 1:1 invariant the parser and exporter both enforce.
    if (candidate.elevations.length !== candidate.coordinates.length) return false;
    if (!candidate.elevations.every((value) => Number.isFinite(value))) return false;
  }

  return true;
};

/** Write a course's geometry. Returns false when nothing was persisted. */
export const writeCourseGeometry = async (
  id: string,
  geometry: StoredCourseGeometry,
): Promise<boolean> => {
  const file = courseFile(id);
  if (file === null) return false;
  if (!(await ensureDirectory())) return false;

  try {
    await FileSystem.writeAsStringAsync(
      file,
      JSON.stringify({
        coordinates: geometry.coordinates,
        elevations: geometry.elevations,
      }),
    );
    return true;
  } catch {
    return false;
  }
};

/**
 * Read a course's geometry back.
 *
 * Validates on read rather than trusting the file: it survives app upgrades,
 * and a truncated write (storage full, kill mid-write) would otherwise reach
 * the router as malformed geometry.
 */
export const readCourseGeometry = async (
  id: string,
): Promise<StoredCourseGeometry | null> => {
  const file = courseFile(id);
  if (file === null) return null;

  try {
    const raw = await FileSystem.readAsStringAsync(file);
    const parsed: unknown = JSON.parse(raw);
    return isStoredGeometry(parsed) ? parsed : null;
  } catch {
    return null;
  }
};

/** Delete a course's geometry. Missing files are not an error. */
export const deleteCourseGeometry = async (id: string): Promise<void> => {
  const file = courseFile(id);
  if (file === null) return;

  try {
    await FileSystem.deleteAsync(file, { idempotent: true });
  } catch {
    // Nothing to do — the metadata row is removed regardless, so a file we
    // failed to delete is orphaned rather than resurrected.
  }
};

/**
 * Remove geometry files with no metadata row pointing at them.
 *
 * Metadata lives in the persisted store and geometry on disk, so the two can
 * drift: a delete whose file removal failed, or a store rollback. Without a
 * sweep those files are invisible and permanent.
 */
export const pruneOrphanedCourses = async (
  knownIds: readonly string[],
): Promise<number> => {
  const dir = courseDirectory();
  if (dir === null) return 0;

  try {
    const info = await FileSystem.getInfoAsync(dir);
    if (!info.exists) return 0;

    const files = await FileSystem.readDirectoryAsync(dir);
    const known = new Set(knownIds);
    let removed = 0;

    for (const fileName of files) {
      if (!fileName.endsWith('.json')) continue;
      const id = fileName.slice(0, -'.json'.length);
      if (known.has(id)) continue;

      await FileSystem.deleteAsync(`${dir}${fileName}`, { idempotent: true });
      removed += 1;
    }

    return removed;
  } catch {
    return 0;
  }
};
