/**
 * Saving a generated loop to the handset.
 *
 * Deliberately NOT `saved_routes`. That table stores origin, destination and
 * waypoints and re-routes on open — it never stores geometry. A loop cannot
 * survive that: its destination IS its origin, so a re-route asks for the
 * shortest way from a point to itself. Even storing the synthesized ring as
 * waypoints only reproduces the line by re-asking OSRM, which costs a network
 * round trip, fails offline, and drops `source: 'generated_loop'` — the marker
 * that stops navigation rerouting the rider home mid-loop.
 *
 * So a saved loop is stored the way an imported course is: metadata in the
 * device-scoped store so the list renders without disk reads, and the route
 * itself in one JSON file per loop.
 *
 * Unlike a course, the whole `RouteOption` is written rather than bare
 * geometry. A course arrives as a line with no turn data and has its
 * instructions synthesized on open; a loop came from OSRM complete with steps,
 * risk segments and an elevation profile, and `geometryPolyline6` is a compact
 * string, so keeping the object whole is both smaller than re-deriving it and
 * exactly faithful to the loop the rider chose.
 *
 * `documentDirectory`, never `cacheDirectory` — the cache is OS-evictable and
 * a saved loop disappearing between sessions is the one failure this cannot
 * have. Generation costs a session from a monthly quota, so a lost loop is not
 * merely re-findable.
 */
import type { Coordinate, RouteOption } from '@defensivepedal/core';

// Static import — a dynamic `await import()` of expo-file-system fails
// silently in Hermes release bytecode on this project. Legacy API matches the
// rest of the codebase.
import * as FileSystem from 'expo-file-system/legacy';

const LOOP_DIR_NAME = 'saved-loops';

/** Row shown in the Routes sheet. Persisted in the Zustand store. */
export interface SavedLoopMeta {
  readonly id: string;
  readonly name: string;
  readonly distanceMeters: number;
  readonly climbMeters: number | null;
  /** So the list can show the shape without reading the file back. */
  readonly unpavedShare: number;
  readonly createdAt: string;
}

/** What a saved loop file holds. */
export interface StoredLoop {
  readonly route: RouteOption;
  /** Where the rider sets off and returns — both ends of a loop. */
  readonly start: Coordinate;
}

const loopDirectory = (): string | null => {
  const base = FileSystem.documentDirectory;
  return base === null ? null : `${base}${LOOP_DIR_NAME}/`;
};

const loopFile = (id: string): string | null => {
  const dir = loopDirectory();
  // `id` is generated by us, never user input, but a path separator sneaking
  // in would escape the directory — cheap to refuse outright.
  if (dir === null || id.includes('/') || id.includes('\\') || id.includes('..')) {
    return null;
  }
  return `${dir}${id}.json`;
};

const ensureDirectory = async (): Promise<boolean> => {
  const dir = loopDirectory();
  if (dir === null) return false;

  try {
    const info = await FileSystem.getInfoAsync(dir);
    if (!info.exists) {
      await FileSystem.makeDirectoryAsync(dir, { intermediates: true });
    }
    return true;
  } catch {
    return false;
  }
};

/** Identifier for a newly saved loop. */
export const createSavedLoopId = (): string =>
  `loop-${Date.now()}-${Math.floor(Math.random() * 1e6).toString(36)}`;

const isStoredLoop = (value: unknown): value is StoredLoop => {
  if (value === null || typeof value !== 'object') return false;
  const candidate = value as { route?: unknown; start?: unknown };

  const start = candidate.start as { lat?: unknown; lon?: unknown } | undefined;
  if (
    start === undefined ||
    start === null ||
    !Number.isFinite(start.lat) ||
    !Number.isFinite(start.lon)
  ) {
    return false;
  }

  const route = candidate.route as Partial<RouteOption> | undefined;
  if (route === undefined || route === null || typeof route !== 'object') {
    return false;
  }
  // Geometry and distance are what make it rideable; without either the router
  // and the HUD both get nonsense.
  if (typeof route.geometryPolyline6 !== 'string' || route.geometryPolyline6.length === 0) {
    return false;
  }
  if (!Number.isFinite(route.distanceMeters) || (route.distanceMeters ?? 0) <= 0) {
    return false;
  }
  // The marker that suppresses auto-reroute. A saved loop that lost it would
  // be silently re-routed home mid-ride, so refuse to load one rather than
  // ride it unprotected.
  if (route.source !== 'generated_loop') return false;
  if (!Array.isArray(route.steps)) return false;

  return true;
};

/** Write a saved loop. Returns false when nothing was persisted. */
export const writeSavedLoop = async (
  id: string,
  loop: StoredLoop,
): Promise<boolean> => {
  const file = loopFile(id);
  if (file === null) return false;
  if (!(await ensureDirectory())) return false;

  try {
    await FileSystem.writeAsStringAsync(
      file,
      JSON.stringify({ route: loop.route, start: loop.start }),
    );
    return true;
  } catch {
    return false;
  }
};

/**
 * Read a saved loop back.
 *
 * Validates on read rather than trusting the file: it survives app upgrades,
 * and a truncated write (storage full, kill mid-write) would otherwise reach
 * navigation as a malformed route.
 */
export const readSavedLoop = async (id: string): Promise<StoredLoop | null> => {
  const file = loopFile(id);
  if (file === null) return null;

  try {
    const raw = await FileSystem.readAsStringAsync(file);
    const parsed: unknown = JSON.parse(raw);
    return isStoredLoop(parsed) ? parsed : null;
  } catch {
    return null;
  }
};

/** Delete a saved loop's file. Missing files are not an error. */
export const deleteSavedLoop = async (id: string): Promise<void> => {
  const file = loopFile(id);
  if (file === null) return;

  try {
    await FileSystem.deleteAsync(file, { idempotent: true });
  } catch {
    // Nothing to do — the metadata row is removed regardless, so a file we
    // failed to delete is orphaned rather than resurrected.
  }
};

/**
 * Remove loop files with no metadata row pointing at them.
 *
 * Metadata lives in the persisted store and the route on disk, so the two can
 * drift: a delete whose file removal failed, or a store rollback. Without a
 * sweep those files are invisible and permanent.
 */
export const pruneOrphanedLoops = async (
  knownIds: readonly string[],
): Promise<number> => {
  const dir = loopDirectory();
  if (dir === null) return 0;

  try {
    const info = await FileSystem.getInfoAsync(dir);
    if (!info.exists) return 0;

    const files = await FileSystem.readDirectoryAsync(dir);
    const known = new Set(knownIds);
    let removed = 0;

    for (const fileName of files) {
      if (!fileName.endsWith('.json')) continue;
      const id = fileName.slice(0, -'.json'.length);
      if (known.has(id)) continue;

      await FileSystem.deleteAsync(`${dir}${fileName}`, { idempotent: true });
      removed += 1;
    }

    return removed;
  } catch {
    return 0;
  }
};
