-- Scenic scoring for recreational loop selection.
--
-- Mirrors road_risk_data: per-way geometry + a score, spatially joined against
-- a route. Generated by OSRM_Server/generate_way_scenic_scores.py from OSM
-- (ODbL — no new attribution obligation beyond what the app already shows).
--
-- DELIBERATELY NOT in the Lua profile and NOT an extract-time overlay. Scenic
-- must never change what the safety graph considers routable; it only reorders
-- candidates the safety graph already produced.

create table if not exists scenic_way_scores (
  way_id       bigint primary key,
  -- [-1, 1]: negative is actively unpleasant (industrial, beside a trunk road),
  -- positive is scenic. Zero means "scored, and unremarkable" — distinct from
  -- absent, which means "not scored", so the two are never confused.
  scenic_score real not null check (scenic_score >= -1 and scenic_score <= 1),
  highway      text,
  name         text,
  geom         geometry(LineString, 4326) not null,
  created_at   timestamptz not null default now()
);

create index if not exists scenic_way_scores_geom_idx
  on scenic_way_scores using gist (geom);

-- Read-only to the app; writes are service-role only, as with road_risk_data.
alter table scenic_way_scores enable row level security;

drop policy if exists scenic_way_scores_read on scenic_way_scores;
create policy scenic_way_scores_read on scenic_way_scores
  for select using (true);

revoke insert, update, delete, truncate on scenic_way_scores from anon, authenticated;
grant select on scenic_way_scores to anon, authenticated;

-- ---------------------------------------------------------------------------
-- get_segmented_scenic_route
-- ---------------------------------------------------------------------------
-- Takes a GeoJSON LineString, breaks it into 2-point segments, and attaches the
-- scenic score of the nearest scored way to each.
--
-- PROBES FROM THE SEGMENT MIDPOINT, not the segment itself (error-log #79). A
-- 2-point segment is at distance exactly 0 from every road meeting at an
-- intersection node, so `order by ST_Distance(...) limit 1` becomes a coin flip
-- there — 56% of Bucharest route segments were such ties, with an average 31
-- point score spread. The midpoint has one nearest road. `<->` gives the index
-- an ordering it can use; the whole-segment fallback keeps coverage identical
-- for the rare segment whose midpoint finds nothing.
create or replace function get_segmented_scenic_route(route_geojson jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
    osrm_geom geometry;
    result_geojson jsonb;
begin
    osrm_geom := ST_SetSRID(ST_GeomFromGeoJSON(route_geojson), 4326);

    with route_segments as (
        select (ST_DumpSegments(osrm_geom)).geom as segment_geom
    ),
    scored_segments as (
        select
            s.segment_geom as geom,
            coalesce(
                (
                    select w.scenic_score
                    from scenic_way_scores w
                    where ST_DWithin(
                        ST_LineInterpolatePoint(s.segment_geom, 0.5), w.geom, 0.0002
                    )
                    order by ST_LineInterpolatePoint(s.segment_geom, 0.5) <-> w.geom
                    limit 1
                ),
                (
                    select w.scenic_score
                    from scenic_way_scores w
                    where ST_DWithin(s.segment_geom, w.geom, 0.0002)
                    order by s.segment_geom <-> w.geom
                    limit 1
                )
            ) as scenic_score
        from route_segments s
    ),
    filtered_segments as (
        select geom, scenic_score
        from scored_segments
        where scenic_score is not null
    )
    select jsonb_build_object(
        'type', 'FeatureCollection',
        'features', coalesce(jsonb_agg(
            jsonb_build_object(
                'type', 'Feature',
                'geometry', ST_AsGeoJSON(geom)::jsonb,
                'properties', jsonb_build_object('scenic_score', scenic_score)
            )
        ), '[]'::jsonb)
    )
    into result_geojson
    from filtered_segments;

    return result_geojson;
end;
$$;

-- ---------------------------------------------------------------------------
-- get_scenic_vias
-- ---------------------------------------------------------------------------
-- Scenic via-point candidates on a ring around a start, for loop generation.
--
-- Returns at most `max_per_sector` points per compass sector so a loop cannot
-- fold back on itself by drawing every via-point from one direction — the ring
-- is divided into 8 sectors and each contributes its best candidates.
create or replace function get_scenic_vias(
    start_lat double precision,
    start_lon double precision,
    ring_radius_m double precision,
    ring_tolerance_m double precision default 3000,
    min_score real default 0.6,
    max_per_sector integer default 2
)
returns jsonb
language plpgsql
stable
as $$
declare
    origin geography;
    result_json jsonb;
begin
    origin := ST_SetSRID(ST_MakePoint(start_lon, start_lat), 4326)::geography;

    with candidates as (
        select
            w.way_id,
            w.scenic_score,
            w.name,
            ST_LineInterpolatePoint(w.geom, 0.5) as pt,
            ST_Distance(ST_LineInterpolatePoint(w.geom, 0.5)::geography, origin) as dist_m
        from scenic_way_scores w
        where w.scenic_score >= min_score
          and ST_DWithin(
              ST_LineInterpolatePoint(w.geom, 0.5)::geography,
              origin,
              ring_radius_m + ring_tolerance_m
          )
    ),
    on_ring as (
        select *,
            -- 0..7, clockwise from north.
            floor(
                (degrees(ST_Azimuth(origin::geometry, pt))::numeric + 22.5) / 45
            )::int % 8 as sector
        from candidates
        where dist_m >= ring_radius_m - ring_tolerance_m
    ),
    ranked as (
        select *,
            row_number() over (
                partition by sector order by scenic_score desc, dist_m asc
            ) as rn
        from on_ring
    )
    select coalesce(jsonb_agg(
        jsonb_build_object(
            'wayId', way_id,
            'scenicScore', scenic_score,
            'name', name,
            'lat', ST_Y(pt),
            'lon', ST_X(pt),
            'sector', sector,
            'distanceMeters', round(dist_m::numeric, 1)
        )
        order by sector, rn
    ), '[]'::jsonb)
    into result_json
    from ranked
    where rn <= max_per_sector;

    return result_json;
end;
$$;
