-- Base schema: tables created before the ordered migration system.
-- Reconstructed from the live Supabase database on 2026-04-02.
-- These tables were originally created via legacy SQL scripts that are
-- now corrupted/unrecoverable in supabase/migrations/legacy/.
--
-- All statements use IF NOT EXISTS / IF EXISTS guards so they are safe
-- to run against an existing database that already has these tables.

-- ---------------------------------------------------------------------------
-- Enable PostGIS (required for road_risk_data and trips geography columns)
-- ---------------------------------------------------------------------------
create extension if not exists postgis with schema extensions;

-- ---------------------------------------------------------------------------
-- 1. road_risk_data — pre-computed road segment risk scores
-- ---------------------------------------------------------------------------
create table if not exists road_risk_data (
  id integer primary key generated by default as identity,
  name varchar,
  highway varchar,
  raw_risk double precision,
  way_id integer,
  is_urban boolean,
  risk_factors json,
  risk_score double precision,
  geom geometry(Geometry, 4326)
);

create index if not exists road_risk_data_geom_idx
  on road_risk_data using gist (geom);

alter table road_risk_data enable row level security;

do $$ begin
  drop policy if exists "Allow public read access to road_risk_data" on road_risk_data;
  create policy "Allow public read access to road_risk_data"
    on road_risk_data for select
    using (true);
end $$;

grant select on road_risk_data to service_role;
grant select on road_risk_data to authenticated;
grant select on road_risk_data to anon;

-- ---------------------------------------------------------------------------
-- 2. trips — trip start/end records
-- ---------------------------------------------------------------------------
create table if not exists trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete set null,
  start_location_text text,
  start_location geography(Point, 4326),
  destination_text text,
  destination_location geography(Point, 4326),
  distance_meters numeric,
  started_at timestamptz default now(),
  ended_at timestamptz,
  end_reason text
);

alter table trips enable row level security;

do $$ begin
  drop policy if exists "Allow public select on trips" on trips;
  create policy "Allow public select on trips"
    on trips for select
    using (true);

  drop policy if exists "Allow public insert on trips" on trips;
  create policy "Allow public insert on trips"
    on trips for insert
    with check (true);

  drop policy if exists "Allow public update on trips" on trips;
  create policy "Allow public update on trips"
    on trips for update
    using (true)
    with check (true);
end $$;

-- ---------------------------------------------------------------------------
-- 3. hazards — user-reported road hazards
-- ---------------------------------------------------------------------------
create table if not exists hazards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete set null,
  location jsonb not null,
  reported_at timestamptz not null default now(),
  day date not null default current_date,
  time_of_day time not null default current_time,
  created_at timestamptz not null default now(),
  hazard_type text,
  confirm_count integer not null default 0,
  deny_count integer not null default 0,
  pass_count integer not null default 0,
  last_confirmed_at timestamptz,
  expires_at timestamptz default (now() + interval '24 hours'),
  constraint hazards_hazard_type_check check (
    hazard_type is null or hazard_type = any(array[
      'illegally_parked_car', 'blocked_bike_lane', 'missing_bike_lane',
      'pothole', 'poor_surface', 'narrow_street', 'dangerous_intersection',
      'construction', 'aggressive_traffic', 'other'
    ])
  )
);

alter table hazards enable row level security;

do $$ begin
  drop policy if exists "Allow public select on hazards" on hazards;
  create policy "Allow public select on hazards"
    on hazards for select
    using (true);

  drop policy if exists "Allow public insert on hazards" on hazards;
  create policy "Allow public insert on hazards"
    on hazards for insert
    with check (true);
end $$;

-- ---------------------------------------------------------------------------
-- 4. navigation_feedback — post-trip safety ratings
-- ---------------------------------------------------------------------------
create table if not exists navigation_feedback (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  start_location text,
  destination text,
  distance_km numeric,
  duration_minutes integer,
  rating integer check (rating >= 1 and rating <= 5),
  feedback_text text,
  created_at timestamptz default timezone('utc', now()),
  user_id uuid references auth.users on delete set null
);

alter table navigation_feedback enable row level security;

do $$ begin
  drop policy if exists "Allow reading feedback" on navigation_feedback;
  create policy "Allow reading feedback"
    on navigation_feedback for select
    using (true);

  drop policy if exists "Allow anonymous feedback insertion" on navigation_feedback;
  create policy "Allow anonymous feedback insertion"
    on navigation_feedback for insert
    with check (true);
end $$;
