-- Staging table for the v22 (RO + ES) bulk reload of road_risk_data.
--
-- Schema mirrors the live road_risk_data table exactly so the rename swap
-- at migration 202605270004 produces an identical-looking table.
--
-- Deliberately NO indexes and NO RLS at this stage:
--  * Indexes are dropped during bulk ogr2ogr/psycopg-COPY loads for
--    5-10x speedup; the GiST index is created post-load by
--    scripts/road-risk-data/build_index.py.
--  * RLS + grants are attached in migration 202605270002 immediately
--    before the rename swap so the policy/grants follow the staging
--    table when it takes over the `road_risk_data` name.
--
-- Safe to re-run: IF NOT EXISTS guards on table creation. If a previous
-- aborted run left a partial road_risk_data_v22 table, drop it manually
-- with `DROP TABLE road_risk_data_v22` before re-applying.
--
-- Full pipeline context: docs/runbooks/road-risk-data.md

create table if not exists public.road_risk_data_v22 (
  id            integer primary key generated by default as identity,
  name          varchar,
  highway       varchar,
  raw_risk      double precision,
  way_id        integer,
  is_urban      boolean,
  risk_factors  json,
  risk_score    double precision,
  geom          geometry(Geometry, 4326)
);

comment on table public.road_risk_data_v22 is
  'Staging table for road_risk_data v22 (RO + ES, 6.15M rows). '
  'Renamed to road_risk_data after bulk load completes. Created 2026-05-27.';
